version: '3.9'
services:
  webserver:
    build:
      context: ./webserver/docker/develop/nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - './webserver/wordpress:/var/www/html'
    depends_on:
      - db
      - wordpress-fpm
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
    volumes:
      - './webserver/wordpress/dbdata:/var/lib/mysql'
    command: '--default-authentication-plugin=mysql_native_password'

  wordpress-fpm:
    build:
      context: ./webserver
      dockerfile: docker/develop/wordpress-fpm/Dockerfile
    container_name: wordpress-fpm
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
    volumes:
        - './webserver/wordpress:/var/www/html'
    depends_on:
      - db